# Site
name: David Clijsters
description: Data Science and more
meta_description: Data Science and more
logo: /assets/images/logo.png
favicon: /assets/images/favicon.ico
paginate: 6
baseurl:
email: 'david.clijsters@telenet.be'
google_analytics:
disqus: xjekyll
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a1a46b37b0f3600122c23bc&product=sticky-share-buttons"></script>'

# Authors
authors:
  David:
    name: David
    display_name: David
    image: /assets/images/David.jpg
    email: david.clijsters@telenet.be
    web: https://clijda.github.io/
    twitter: DavidClijsters
    description: Hi, I am David Clijsters.

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-seo-tag

permalinks: pretty

# Archives
jekyll-archives:
  enabled:
    - categories
  layouts: archive
  permalinks:
    category: 'category/:name/'

# Other
markdown: kramdown
highlighter: rouge

# SEO
twitter:
  username: DavidClijsters
  card: summary

facebook:
  app_id:
  publisher: 
  admins:

social:
name: David Clijsters
links:
    - https://twitter.com/
    - https://www.facebook.com/
    - https://www.linkedin.com/
    - https://plus.google.com/
    - https://github.com/
